name: hustl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.*
  - opencv=4.0.1
  - numpy=1.16.2
  - scipy=1.2.1
  - scikit-image=0.15.0
  - pillow=6.0.0
  - pytorch=1.0.1
  - torchvision=0.2.2
  - cudatoolkit=10.0
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - jupyter=5.7.8
  - notebook=1.0.0
  - pip:
    - rawpy=0.13.1
    - pyqt5=5.12.1